require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop/cop/betterment.rb
  - rubocop-performance
  - standard
  - rubocop-gitlab-security
inherit_gem:
  standard: config/base.yml
  rubocop-rspec: config/default.yml
  rubocop-gitlab-security: config/default.yml
AllCops:
  TargetRubyVersion: 2.7
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "bin/**/*"
Rails/ActiveRecordCallbacksOrder: # (new in 2.7)
  Enabled: true
Rails/AddColumnIndex: # (new in 2.11)
  Enabled: true
Rails/AfterCommitOverride: # (new in 2.8)
  Enabled: true
Rails/AttributeDefaultBlockValue: # (new in 2.9)
  Enabled: true
Rails/EagerEvaluationLogMessage: # (new in 2.11)
  Enabled: true
Rails/ExpandedDateRange: # (new in 2.11)
  Enabled: true
Rails/FindById: # (new in 2.7)
  Enabled: true
Rails/I18nLocaleAssignment: # (new in 2.11)
  Enabled: true
Rails/Inquiry: # (new in 2.7)
  Enabled: true
Rails/MailerName: # (new in 2.7)
  Enabled: true
Rails/MatchRoute: # (new in 2.7)
  Enabled: true
Rails/NegateInclude: # (new in 2.7)
  Enabled: true
Rails/Pluck: # (new in 2.7)
  Enabled: true
Rails/PluckInWhere: # (new in 2.7)
  Enabled: true
Rails/RedundantTravelBack: # (new in 2.12)
  Enabled: true
Rails/RenderInline: # (new in 2.7)
  Enabled: true
Rails/RenderPlainText: # (new in 2.7)
  Enabled: true
Rails/ShortI18n: # (new in 2.7)
  Enabled: true
Rails/SkipsModelValidations:
  Enabled: false
# This is not safe for Postgres
Rails/SquishedSQLHeredocs: # (new in 2.8)
  Enabled: false
Rails/TimeZoneAssignment: # (new in 2.10)
  Enabled: true
Rails/UnusedIgnoredColumns: # (new in 2.11)
  Enabled: true
Rails/WhereEquals: # (new in 2.9)
  Enabled: true
Rails/WhereExists: # (new in 2.7)
  Enabled: true
Rails/WhereNot: # (new in 2.8)
  Enabled: true
Rails/CompactBlank: # new in 2.13
  Enabled: true
Rails/DurationArithmetic: # new in 2.13
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true
Rails/RootJoinChain: # new in 2.13
  Enabled: true
Style/BlockDelimiters:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
  Exclude:
    - "spec/**/*.rb"
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Betterment/SpecHelperRequiredOutsideSpecDir:
  Enabled: false
Betterment/UnscopedFind:
  Enabled: true
Betterment/AllowlistBlocklist:
  Enabled: true
Betterment/ActiveJobPerformable:
  Enabled: false
GitlabSecurity/JsonSerialization:
  Enabled: false
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/MultipleExpectations:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Max: 10
RSpec/ExampleLength:
  Max: 20
RSpec/FilePath:
  Enabled: false
Rails/ApplicationRecord:
  Exclude:
    - 'db/migrate/*'
